const $=s=>document.querySelector(s);let notes=[],selectedId=null,currentImageId=null,toastTimer,templates=[],wallpaperCandidateIds=[],overlayCandidateIds=[];
function notify(message,error=false){const t=$('#toast');t.textContent=message;t.className=error?'show error':'show';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.className='',3500)}
async function api(url,options={}){const r=await fetch(url,options);let d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.detail||'処理に失敗しました。');return d}
const escapeHtml=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};
function localDate(days=0){const d=new Date();d.setDate(d.getDate()+days);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function formData(){const n=notes.find(x=>x.id===selectedId)||{};return{title:$('#title').value.trim(),character:$('#character').value.trim(),category:$('#category').value,bullet_points:$('#bullet-points').value,goal:$('#goal').value,notes:$('#notes').value,priority:$('#priority').value,proficiency_level:Number($('#proficiency-level').value),last_practiced_at:n.last_practiced_at||null,next_review_at:$('#next-review-at').value||null,success_count:n.success_count||0,failure_count:n.failure_count||0,archived:$('#archived').checked,favorite:$('#favorite').checked,tags:$('#tags').value.trim(),review_status:$('#review-status').value}}
const optionsData=()=>({support_style:$('#support-style').value,text_position:$('#text-position').value,theme_color:$('#theme-color').value});
function renderNotes(){ $('#note-count').textContent=notes.length;$('#note-list').innerHTML=notes.length?notes.map(n=>`<div class="note-card ${n.id===selectedId?'active':''}" data-id="${n.id}"><strong>${n.favorite?'★ ':''}${escapeHtml(n.title)}</strong><div class="note-meta"><span>${escapeHtml(n.character||n.category||'未分類')}・Lv${n.proficiency_level}</span><span class="priority-${n.priority}">${n.priority.toUpperCase()}</span></div></div>`).join(''):'<div class="empty-list">条件に合うメモがありません。</div>';document.querySelectorAll('.note-card').forEach(e=>e.onclick=()=>selectNote(Number(e.dataset.id)))}
function selectNote(id){const n=notes.find(x=>x.id===id);if(!n)return;selectedId=id;for(const[k,s]of Object.entries({title:'#title',character:'#character',category:'#category',bullet_points:'#bullet-points',goal:'#goal',notes:'#notes',priority:'#priority'}))$(s).value=n[k]||(k==='priority'?'medium':'');$('#proficiency-level').value=n.proficiency_level;$('#next-review-at').value=n.next_review_at||'';$('#review-status').value=n.review_status;$('#tags').value=n.tags||'';$('#favorite').checked=!!n.favorite;$('#archived').checked=!!n.archived;$('#practice-counts').textContent=`成功 ${n.success_count} / 失敗・迷い ${n.failure_count}`;$('#delete-note').disabled=false;$('#save-state').textContent='編集中';renderNotes()}
function newNote(){selectedId=null;$('#note-form').reset();$('#priority').value='medium';$('#proficiency-level').value='0';$('#review-status').value='new';$('#next-review-at').value=localDate(1);$('#delete-note').disabled=true;$('#save-state').textContent='新規メモ';$('#practice-counts').textContent='';renderNotes();$('#title').focus()}
function filterParams(){const p=new URLSearchParams();for(const[id,key]of[['filter-q','q'],['filter-character','character'],['filter-category','category'],['filter-priority','priority'],['filter-proficiency','proficiency'],['filter-tag','tag'],['filter-archive','archive']])if($('#'+id).value)p.set(key,$('#'+id).value);if($('#filter-favorite').checked)p.set('favorite','true');return p}
async function loadNotes(){notes=await api('/api/notes?'+filterParams());renderNotes()}

$('#note-form').onsubmit=async e=>{e.preventDefault();try{const saved=await api(selectedId?`/api/notes/${selectedId}`:'/api/notes',{method:selectedId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formData())});selectedId=saved.id;await Promise.all([loadNotes(),loadOverlayNotes(),loadDashboard(),loadCandidates()]);$('#save-state').textContent='保存済み';notify('メモを保存しました。')}catch(e){notify(e.message,true)}};
$('#new-note').onclick=newNote;$('#delete-note').onclick=async()=>{if(!selectedId||!confirm('このメモを削除しますか？'))return;try{await api(`/api/notes/${selectedId}`,{method:'DELETE'});newNote();await Promise.all([loadNotes(),loadOverlayNotes(),loadDashboard(),loadCandidates()]);notify('メモを削除しました。')}catch(e){notify(e.message,true)}};
let filterTimer;document.querySelectorAll('.filters input,.filters select').forEach(e=>{e.oninput=()=>{clearTimeout(filterTimer);filterTimer=setTimeout(loadNotes,180)}});

async function loadTemplates(){templates=await api('/api/templates');$('#template-buttons').innerHTML=templates.map(t=>`<button type="button" data-template="${t.id}">${escapeHtml(t.name)}</button>`).join('');document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const t=templates.find(x=>x.id===Number(b.dataset.template));newNote();$('#title').value=t.name+'：';$('#category').value=t.category;$('#bullet-points').value=t.bullet_points;$('#goal').value=t.goal;notify(`${t.name}テンプレートを適用しました。`)})}

async function loadDashboard(){const[due,list]=await Promise.all([api('/api/review/dashboard'),api('/api/review/today')]);for(const k of['due','new','active','overdue'])$('#stat-'+k).textContent=due[k];$('#today-list').innerHTML=list.length?list.map(n=>`<div class="review-item"><div><strong>${escapeHtml(n.title)}</strong><div class="muted">${escapeHtml(n.character||'未指定')}・Lv${n.proficiency_level}・期限 ${n.next_review_at}</div></div><div class="review-actions"><select data-result="${n.id}"><option>忘れていた</option><option>少し迷った</option><option selected>問題なくできた</option><option>実戦で成功した</option></select><button data-review="${n.id}" class="primary">記録</button><button data-wall-add="${n.id}">壁紙候補へ</button><button data-overlay-add="${n.id}">常駐候補へ</button></div></div>`).join(''):'<div class="empty-section">今日の復習は完了です。</div>';document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>submitReview(Number(b.dataset.review)));document.querySelectorAll('[data-wall-add]').forEach(b=>b.onclick=()=>addCandidate(Number(b.dataset.wallAdd),'wall'));document.querySelectorAll('[data-overlay-add]').forEach(b=>b.onclick=()=>addCandidate(Number(b.dataset.overlayAdd),'overlay'))}
async function submitReview(id){try{const result=$(`[data-result="${id}"]`).value;const d=await api(`/api/notes/${id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({result,comment:''})});notify(`記録しました。次回は ${d.next_review_at} です。`);await Promise.all([loadDashboard(),loadNotes(),loadCandidates()])}catch(e){notify(e.message,true)}}
$('#refresh-dashboard').onclick=loadDashboard;

let wallItems=[],overlayItems=[];async function loadCandidates(){[wallItems,overlayItems]=await Promise.all([api('/api/candidates/wallpaper'),api('/api/candidates/overlay')]);wallpaperCandidateIds=wallItems.map(n=>n.id);overlayCandidateIds=overlayItems.map(n=>n.id);renderCandidates()}
function renderCandidates(){const render=(items,ids,type)=>items.length?items.map(n=>`<label class="candidate-item"><input type="checkbox" data-candidate-type="${type}" value="${n.id}" ${ids.includes(n.id)?'checked':''}><div><strong>${escapeHtml(n.title)}</strong><span>Lv${n.proficiency_level}・${escapeHtml(n.priority)}・スコア ${n.candidate_score}</span></div></label>`).join(''):'<div class="empty-section">候補なし</div>';$('#wallpaper-candidates').innerHTML=render(wallItems,wallpaperCandidateIds,'wall');$('#overlay-candidates').innerHTML=render(overlayItems,overlayCandidateIds,'overlay');document.querySelectorAll('[data-candidate-type]').forEach(c=>c.onchange=()=>{const target=c.dataset.candidateType==='wall'?wallpaperCandidateIds:overlayCandidateIds;const id=Number(c.value);if(c.checked&&!target.includes(id))target.push(id);if(!c.checked)target.splice(target.indexOf(id),1)})}
function addCandidate(id,type){const target=type==='wall'?wallpaperCandidateIds:overlayCandidateIds;if(!target.includes(id))target.push(id);const note=notes.find(n=>n.id===id);const items=type==='wall'?wallItems:overlayItems;if(note&&!items.some(n=>n.id===id))items.push(note);renderCandidates();notify(type==='wall'?'壁紙候補へ追加しました。':'常駐メモ候補へ追加しました。')}
$('#refresh-candidates').onclick=loadCandidates;$('#candidate-prompt').onclick=async()=>{if(!wallpaperCandidateIds.length)return notify('候補を選択してください。',true);try{const d=await api('/api/prompt/candidates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note_ids:wallpaperCandidateIds.slice(0,5),options:optionsData()})});$('#prompt-output').value=d.prompt;location.hash='';$('#prompt-output').scrollIntoView({behavior:'smooth'});notify('候補から壁紙プロンプトを生成しました。')}catch(e){notify(e.message,true)}};
$('#candidate-overlay').onclick=()=>{const ids=overlayCandidateIds.slice(0,6);if(!ids.length)return notify('候補を選択してください。',true);renderOverlayNotePicker(ids);$('#overlay-settings').scrollIntoView({behavior:'smooth'});notify('候補を常駐メモへ選択しました。保存してください。')};

$('#generate-prompt').onclick=async()=>{if(!formData().title)return notify('先にタイトルを入力してください。',true);try{const d=await api('/api/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:formData(),options:optionsData()})});$('#prompt-output').value=d.prompt;notify('プロンプトを生成しました。')}catch(e){notify(e.message,true)}};
async function copyPrompt(){if(!$('#prompt-output').value)throw new Error('先にプロンプトを生成してください。');await navigator.clipboard.writeText($('#prompt-output').value)}$('#copy-prompt').onclick=async()=>{try{await copyPrompt();notify('クリップボードにコピーしました。')}catch(e){notify(e.message,true)}};$('#copy-open').onclick=async()=>{try{await copyPrompt();window.open('https://chatgpt.com/','_blank','noopener');notify('コピーしてChatGPTを開きました。')}catch(e){notify(e.message,true)}};

const input=$('#image-input'),zone=$('#drop-zone');$('#choose-image').onclick=()=>input.click();input.onchange=()=>input.files[0]&&upload(input.files[0]);['dragenter','dragover'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(n=>zone.addEventListener(n,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>e.dataTransfer.files[0]&&upload(e.dataTransfer.files[0]));
async function upload(file){const data=new FormData();data.append('file',file);try{notify('画像を取り込んでいます…');const image=await api('/api/images'+(selectedId?`?note_id=${selectedId}`:''),{method:'POST',body:data});useImage(image.id,image.preview_url);await loadHistory();notify('画像を取り込み、PNGを作成しました。')}catch(e){notify(e.message,true)}}
function useImage(id,url){currentImageId=id;$('#preview-image').src=url+'?t='+Date.now();$('#preview-image').hidden=false;$('#preview-empty').hidden=true;$('#set-wallpaper').disabled=false;$('#preview-image').scrollIntoView({behavior:'smooth',block:'nearest'})}
$('#set-wallpaper').onclick=async()=>{try{const d=await api('/api/wallpaper',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image_id:currentImageId,note_id:selectedId})});notify(d.message);await loadHistory()}catch(e){notify(e.message,true)}};$('#restore-wallpaper').onclick=async()=>{try{const d=await api('/api/wallpaper/restore',{method:'POST'});notify(d.message)}catch(e){notify(e.message,true)}};

async function loadHistory(){const[images,walls]=await Promise.all([api('/api/images/history'),api('/api/wallpaper/history')]);$('#image-history').innerHTML=images.length?images.map(i=>`<div class="history-card"><img src="${i.preview_url}"><div><strong>${escapeHtml(i.original_name)}</strong><small>${new Date(i.created_at).toLocaleString()}</small><small>${escapeHtml(i.note_title||'メモ未紐付け')}</small><button data-use-image="${i.id}" data-url="${i.preview_url}">再利用</button></div></div>`).join(''):'<div class="empty-section">画像なし</div>';$('#wallpaper-history').innerHTML=walls.length?walls.map(w=>`<div class="history-card"><img src="${w.preview_url}"><div><strong>${w.favorite?'★ ':''}${escapeHtml(w.note_title||'壁紙')}</strong><small>${new Date(w.set_at).toLocaleString()}</small><button data-reapply="${w.id}">再設定</button> <button data-wall-fav="${w.id}">★</button></div></div>`).join(''):'<div class="empty-section">履歴なし</div>';document.querySelectorAll('[data-use-image]').forEach(b=>b.onclick=()=>useImage(Number(b.dataset.useImage),b.dataset.url));document.querySelectorAll('[data-reapply]').forEach(b=>b.onclick=async()=>{try{const d=await api(`/api/wallpaper/history/${b.dataset.reapply}/apply`,{method:'POST'});notify(d.message);loadHistory()}catch(e){notify(e.message,true)}});document.querySelectorAll('[data-wall-fav]').forEach(b=>b.onclick=async()=>{await api(`/api/wallpaper/history/${b.dataset.wallFav}/favorite`,{method:'POST'});loadHistory()})}$('#refresh-history').onclick=loadHistory;

const overlayFields={monitor_index:'#overlay-monitor',position_preset:'#overlay-position',x:'#overlay-x',y:'#overlay-y',width:'#overlay-width',height:'#overlay-height',text_size:'#overlay-text-size',background_color:'#overlay-bg',text_color:'#overlay-color'};const overlayHotkeys={toggle_visible:'Ctrl+Alt+M',toggle_topmost:'Ctrl+Alt+T',toggle_click_through:'Ctrl+Alt+C',open_editor:'Ctrl+Alt+E'};let selectedOverlayNoteIds=[],overlayNotes=[];
async function loadOverlayNotes(){overlayNotes=await api('/api/notes?archive=active');renderOverlayNotePicker()}
function renderOverlayNotePicker(ids=selectedOverlayNoteIds){selectedOverlayNoteIds=ids.filter((id,i,a)=>a.indexOf(id)===i&&overlayNotes.some(n=>n.id===id)).slice(0,6);$('#overlay-note-picker').innerHTML=overlayNotes.length?overlayNotes.map(n=>`<label class="overlay-note-option ${selectedOverlayNoteIds.includes(n.id)?'selected':''}"><input type="checkbox" value="${n.id}" ${selectedOverlayNoteIds.includes(n.id)?'checked':''}><span class="note-number">${String(selectedOverlayNoteIds.indexOf(n.id)+1).padStart(2,'0')}</span><span><strong>${escapeHtml(n.title)}</strong><small>${escapeHtml(n.character||'ALL')} / ${escapeHtml(n.category||'GENERAL')}</small></span><em>${n.priority.toUpperCase()}</em></label>`).join(''):'<div class="empty-section">先に戦略メモを保存してください。</div>';$('#overlay-selection-count').textContent=`${selectedOverlayNoteIds.length} / 6`;const first=overlayNotes.find(n=>n.id===selectedOverlayNoteIds[0]);$('#overlay-preview-title').textContent=first?first.title:'メモを選択してください';$('#overlay-preview-meta').textContent=first?`${first.character||'ALL'} · ${first.category||'GENERAL'}${selectedOverlayNoteIds.length>1?` +${selectedOverlayNoteIds.length-1}`:''}`:'戦略カードがここに表示されます';document.querySelectorAll('#overlay-note-picker input').forEach(c=>c.onchange=()=>{const id=Number(c.value);if(c.checked){if(selectedOverlayNoteIds.length>=6){c.checked=false;return notify('常駐メモは最大6件です。',true)}selectedOverlayNoteIds.push(id)}else selectedOverlayNoteIds=selectedOverlayNoteIds.filter(x=>x!==id);renderOverlayNotePicker()})}
function setOverlayForm(s){for(const[k,v]of Object.entries(overlayFields))$(v).value=s[k];renderOverlayNotePicker(s.selected_note_ids||[]);$('#overlay-opacity').value=Math.round(s.opacity*100);$('#opacity-value').textContent=Math.round(s.opacity*100)+'%';$('#overlay-topmost').checked=s.always_on_top;$('#overlay-click-through').checked=s.click_through;$('#overlay-visible').checked=s.visible;$('#overlay-autostart').checked=s.auto_start;$('#overlay-form').classList.toggle('free-position',s.position_preset==='自由')}
function getOverlayForm(){const v={};for(const[k,s]of Object.entries(overlayFields))v[k]=$(s).value;for(const k of['monitor_index','x','y','width','height','text_size'])v[k]=Number(v[k]);return{...v,overlay_title:'STRATEGY DECK',overlay_body:'',overlay_mode:'BATTLE PLAN',selected_note_ids:selectedOverlayNoteIds,opacity:Number($('#overlay-opacity').value)/100,always_on_top:$('#overlay-topmost').checked,click_through:$('#overlay-click-through').checked,visible:$('#overlay-visible').checked,auto_start:$('#overlay-autostart').checked,hotkeys:overlayHotkeys}}
async function loadOverlay(){const[s,m]=await Promise.all([api('/api/overlay/settings'),api('/api/overlay/monitors')]);$('#overlay-monitor').innerHTML=m.map(x=>`<option value="${x.index}">${escapeHtml(x.name)} — ${x.width}×${x.height}${x.primary?'（メイン）':''}</option>`).join('');setOverlayForm(s)}$('#overlay-opacity').oninput=e=>$('#opacity-value').textContent=e.target.value+'%';$('#overlay-position').onchange=e=>$('#overlay-form').classList.toggle('free-position',e.target.value==='自由');$('#overlay-form').onsubmit=async e=>{e.preventDefault();if(!selectedOverlayNoteIds.length)return notify('表示する戦略メモを選択してください。',true);try{const d=await api('/api/overlay/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(getOverlayForm())});notify(d.message)}catch(e){notify(e.message,true)}};async function overlayAction(action){try{const d=await api('/api/overlay/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});setOverlayForm(d.settings);notify(d.message)}catch(e){notify(e.message,true)}}$('#overlay-show').onclick=()=>overlayAction('show');$('#overlay-hide').onclick=()=>overlayAction('hide');$('#overlay-toggle-top').onclick=()=>overlayAction('toggle_topmost');$('#overlay-disable-click').onclick=async()=>{if(!$('#overlay-click-through').checked)return notify('クリック透過はすでにOFFです。');$('#overlay-click-through').checked=false;try{const d=await api('/api/overlay/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(getOverlayForm())});notify(d.message)}catch(e){notify(e.message,true)}};

$('#restore-button').onclick=()=>$('#restore-input').click();$('#restore-input').onchange=async()=>{const file=$('#restore-input').files[0];if(!file||!confirm('現在のDBをバックアップ内容で置き換えます。続行しますか？'))return;const data=new FormData();data.append('file',file);try{const d=await api('/api/backup/restore',{method:'POST',body:data});notify(d.message);setTimeout(()=>location.reload(),1200)}catch(e){notify(e.message,true)}};

(async()=>{try{newNote();await loadOverlayNotes();await Promise.all([loadNotes(),loadTemplates(),loadDashboard(),loadCandidates(),loadHistory(),loadOverlay()]);const o=await api('/api/settings/prompt');$('#support-style').value=o.support_style;$('#text-position').value=o.text_position;$('#theme-color').value=o.theme_color}catch(e){notify(e.message,true)}})();
