(() => {
  const translations = {
    '今日の復習':'Today’s review','メモ':'Notes','履歴':'History','常駐メモ':'Overlay','＋ 新規作成':'+ New note','戦略メモ':'Practice notes','全文検索':'Search all text','全カテゴリ':'All categories','全優先度':'All priorities','全習熟度':'All levels','使用中':'Active','アーカイブ':'Archived','すべて':'All','キャラクター':'Subject / character','タグ':'Tags','お気に入りのみ':'Favorites only','更新':'Refresh','新規課題':'New drills','実戦投入中':'In progress','期限切れ':'Overdue','メモ編集':'Edit practice note','新規メモ':'New note','テンプレート：':'Templates:','タイトル':'Title','カテゴリ':'Category','選択してください':'Select','優先度':'Priority','箇条書き本文':'Practice steps','今日の目標':'Today’s target','補足':'Notes','習熟度':'Proficiency','次回復習日':'Next review','復習状態':'Review status','タグ（カンマ区切り）':'Tags (comma-separated)','お気に入り':'Favorite','保存':'Save','削除':'Delete','自動選出':'Smart suggestions','候補を再計算':'Recalculate','壁紙候補':'Wallpaper suggestions','常駐メモ候補':'Overlay suggestions','候補から壁紙プロンプト生成':'Create wallpaper prompt','候補を常駐メモへ反映':'Use in overlay','画像生成プロンプト':'Image prompt','応援スタイル':'Tone','文字配置':'Text position','テーマカラー':'Theme color','プロンプト生成':'Generate prompt','コピー':'Copy','コピーしてChatGPTを開く ↗':'Copy and open ChatGPT ↗','サブディスプレイ常駐メモ':'Desktop practice overlay','表示する戦略メモを選択':'Choose practice notes','保存済みメモから最大6件。選択順に常駐メモへ表示します。':'Choose up to six saved notes. They appear in selection order.','表示先モニター':'Display monitor','メモを選択してください':'Select a note','戦略カードがここに表示されます':'Practice cards appear here','初期位置':'Position','幅':'Width','高さ':'Height','文字サイズ':'Text size','透明度':'Opacity','背景色':'Background','文字色':'Text color','常に最前面':'Always on top','クリック透過':'Click-through','X座標（自由配置）':'X position (custom)','Y座標（自由配置）':'Y position (custom)','起動時に表示':'Show on launch','Windows起動時に自動起動':'Start with Windows','ホットキー':'Hotkeys','表示切替 Ctrl+Alt+M':'Show / hide Ctrl+Alt+M','最前面 Ctrl+Alt+T':'Always on top Ctrl+Alt+T','クリック透過 Ctrl+Alt+C':'Click-through Ctrl+Alt+C','編集画面 Ctrl+Alt+E':'Open editor Ctrl+Alt+E','設定を保存・反映':'Save and apply','表示':'Show','隠す':'Hide','最前面切替':'Toggle topmost','クリック透過を解除':'Disable click-through','画像取り込み・壁紙':'Images and wallpaper','画像をドロップ':'Drop an image','または':'or','画像を選択':'Choose image','壁紙に設定':'Set wallpaper','前の壁紙に戻す':'Restore previous','画像・壁紙履歴':'Image and wallpaper history','取り込んだ画像':'Imported images','設定した壁紙':'Applied wallpapers','バックアップ・復元':'Backup and restore','バックアップをダウンロード':'Download backup','ZIPから復元':'Restore from ZIP','左上':'Top left','右上':'Top right','左下':'Bottom left','右下':'Bottom right','自由':'Custom','忘れていた':'Forgot','少し迷った':'Hesitated','問題なくできた':'Completed','実戦で成功した':'Succeeded in practice','記録':'Record','壁紙候補へ':'Add to wallpaper','常駐候補へ':'Add to overlay','今日の復習は完了です。':'Today’s review is complete.','条件に合うメモがありません。':'No matching notes.','先に戦略メモを保存してください。':'Save a practice note first.','候補なし':'No suggestions','画像なし':'No images','履歴なし':'No history'
  };
  Object.assign(translations,{'コンボ':'Sequence drill','起き攻め':'Follow-up drill','セットプレイ':'Scenario drill','対空':'Reaction drill','確定反撃':'Response drill','守り':'Defense','キャラ対策':'Subject study','実戦課題':'Live practice','0 未着手':'0 Not started','1 見れば出せる':'1 With reference','2 見ずに出せる':'2 From memory','3 実戦で使える':'3 Practice ready','応援':'Encouraging','熱血':'Energetic','落ち着き':'Calm','かわいい':'Friendly','左':'Left','右':'Right','中央':'Center','ネイビー':'Navy','ブラック':'Black','ダークパープル':'Dark purple','ダークグリーン':'Dark green','チャコール':'Charcoal','例：ランクマ前の確認':'Example: reaction practice','例：ジュリ':'Example: General','対空, ランクマ, 要練習':'reaction, timing, focus'});
  const originals=new WeakMap(), attributes=['placeholder','title','aria-label'];
  let language=localStorage.getItem('loopnote-language')||'en';
  function translate(root=document){
    const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
    while(node=walker.nextNode()){if(!originals.has(node))originals.set(node,node.nodeValue);const original=originals.get(node),trimmed=original.trim(),value=translations[trimmed];if(node.parentElement?.tagName==='OPTION'&&!node.parentElement.hasAttribute('value'))node.parentElement.setAttribute('value',trimmed);node.nodeValue=language==='en'&&value?original.replace(trimmed,value):original}
    root.querySelectorAll?.('*').forEach(element=>attributes.forEach(attribute=>{const key=`i18n${attribute}`;if(element.hasAttribute(attribute)&&!element.dataset[key])element.dataset[key]=element.getAttribute(attribute);const original=element.dataset[key];if(original)element.setAttribute(attribute,language==='en'?(translations[original]||original):original)}));
    const placeholders={'#filter-q':['Search all text','全文検索'],'#filter-character':['Subject / character','キャラクター'],'#filter-tag':['Tags','タグ'],'#title':['Example: reaction practice','例：ランクマ前の確認'],'#character':['Example: General','例：ジュリ'],'#tags':['reaction, timing, focus','対空, ランクマ, 要練習']};Object.entries(placeholders).forEach(([selector,values])=>{const element=document.querySelector(selector);if(element)element.placeholder=values[language==='en'?0:1]});document.documentElement.lang=language;document.querySelectorAll('[data-lang]').forEach(button=>button.classList.toggle('active',button.dataset.lang===language));
  }
  document.querySelectorAll('[data-lang]').forEach(button=>button.addEventListener('click',()=>{language=button.dataset.lang;localStorage.setItem('loopnote-language',language);translate();document.documentElement.lang=language}));
  new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===1)translate(node)}))).observe(document.body,{childList:true,subtree:true});
  translate();
})();
